# vim: ft=riscv commentstring=#%s

# Autogenerated file, use 'make sprites' to regenerate.
# Source file [png]: sprites.png

.global D_spritesheet
.section .rodata
D_spritesheet:
  .word 7
  .byte 0b00000000
  .byte 0b00111100
  .byte 0b01000010
  .byte 0b01000010
  .byte 0b01000010
  .byte 0b00111100
  .byte 0b00000000
  .byte 0b00000000 # FIXME: padding
  .byte 0b00000000
  .byte 0b00000000
  .byte 0b00000000
  .byte 0b01000100
  .byte 0b01111110
  .byte 0b01000000
  .byte 0b00000000
  .byte 0b00000000 # FIXME: padding
  .byte 0b00000000
  .byte 0b00000000
  .byte 0b01100100
  .byte 0b01010010
  .byte 0b01010010
  .byte 0b01001100
  .byte 0b00000000
  .byte 0b00000000 # FIXME: padding
  .byte 0b00000000
  .byte 0b00000000
  .byte 0b01000010
  .byte 0b01001010
  .byte 0b01001010
  .byte 0b00110100
  .byte 0b00000000
  .byte 0b00000000 # FIXME: padding
  .byte 0b00000000
  .byte 0b00000000
  .byte 0b00011000
  .byte 0b00010100
  .byte 0b01111110
  .byte 0b00010000
  .byte 0b00000000
  .byte 0b00000000 # FIXME: padding
  .byte 0b00000000
  .byte 0b00000000
  .byte 0b01001110
  .byte 0b01001010
  .byte 0b01001010
  .byte 0b00110010
  .byte 0b00000000
  .byte 0b00000000 # FIXME: padding
  .byte 0b00000000
  .byte 0b00000000
  .byte 0b00111100
  .byte 0b01001010
  .byte 0b01001010
  .byte 0b00110000
  .byte 0b00000000
  .byte 0b00000000 # FIXME: padding
  .byte 0b00000000
  .byte 0b00000000
  .byte 0b00000010
  .byte 0b01100010
  .byte 0b00010010
  .byte 0b00001110
  .byte 0b00000000
  .byte 0b00000000 # FIXME: padding
  .byte 0b00000000
  .byte 0b00000000
  .byte 0b00110100
  .byte 0b01001010
  .byte 0b01001010
  .byte 0b00110100
  .byte 0b00000000
  .byte 0b00000000 # FIXME: padding
  .byte 0b00000000
  .byte 0b00000000
  .byte 0b00001100
  .byte 0b01010010
  .byte 0b01010010
  .byte 0b00111100
  .byte 0b00000000
  .byte 0b00000000 # FIXME: padding
